# Generated by Django 3.1.5 on 2021-01-21 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('default_town_or_city', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('default_building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('default_house_number', models.CharField(blank=True, max_length=40, null=True)),
                ('default_street_address', models.CharField(blank=True, max_length=250, null=True)),
                ('default_province', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('default_barangay', models.CharField(blank=True, max_length=80, null=True)),
                ('default_landmark', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
